# Generated by Django 5.1.4 on 2024-12-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotationtask",
            name="annotations",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
